CC ?= cc
CFLAGS ?= -O2 -Wall -Wextra -std=c99
LDLIBS ?= -lm

# The ncurses interface (./navalm --gui) is built by default.
# If curses is unavailable:  make nogui
GUI_CFLAGS = -DNAVALM_GUI
GUI_SRC    = navgui.c
GUI_LIBS   = -lncurses

SRC = navalm.c navsight.c navcmd.c navrc.c navweb.c nav_engine_x.c nav_stars_x.c
HDR = nav_notice.h nav_engine.h nav_stars_x.h navsight.h navrc.h navweb_page.h

# XEphem libastro, vendored under libastro/ (MIT, see libastro/LICENSE.XEphem)
# deltat.c is excluded: nav_engine_x.c supplies deltat() from the leap-second
# table, which is exact for modern dates (libastro's own table stops in the 2010s).
ASTRO_SRC = $(filter-out libastro/deltat.c,$(wildcard libastro/*.c))
ASTRO_OBJ = $(ASTRO_SRC:.c=.o)
ASTRO_CFLAGS = -O2 -w -std=c99 -Ilibastro

all: navalm

libastro/%.o: libastro/%.c
	$(CC) $(ASTRO_CFLAGS) -c -o $@ $<

libastro.a: $(ASTRO_OBJ)
	ar rcs $@ $(ASTRO_OBJ)

navalm: $(SRC) $(GUI_SRC) $(HDR) libastro.a
	$(CC) $(CFLAGS) $(GUI_CFLAGS) -o $@ $(SRC) $(GUI_SRC) libastro.a $(LDLIBS) $(GUI_LIBS)

nogui: $(SRC) $(HDR) libastro.a
	$(CC) $(CFLAGS) -o navalm $(SRC) libastro.a $(LDLIBS)

stars: navstars.edb tools/mknavstars.sh
	{ echo '/* generated by tools/mknavstars.sh from navstars.edb - do not edit */'; \
	  echo '/* XEphem catalog data: see libastro/LICENSE.XEphem and THIRD_PARTY_NOTICES.md. */'; \
	  echo '#include "nav_stars_x.h"'; echo; \
	  echo 'const NavStarCat nav_star_cat[] = {'; \
	  ./tools/mknavstars.sh navstars.edb; \
	  echo '};'; \
	  echo 'const size_t nav_star_cat_count = sizeof nav_star_cat / sizeof nav_star_cat[0];'; \
	} > nav_stars_x.c

page: page.html
	./mkpage.sh

clean:
	rm -f navalm libastro.a $(ASTRO_OBJ)
