/* generated from page.html by mkpage.sh - do not edit */
#ifndef NAVWEB_PAGE_H
#define NAVWEB_PAGE_H
#define NAVALM_WEB_VERSION "3.3c"
static const char navweb_page[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>navalm</title>\n"
"<style>\n"
":root{\n"
"  --bg:#fbfaf7; --panel:#fff; --ink:#1b1b1a; --dim:#6b6a66; --line:#ddd9d0;\n"
"  --accent:#2f5d50; --warn:#8a4b2a; --mark:#eef3f0;\n"
"  --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  --serif:'Iowan Old Style','Palatino Linotype',Palatino,Georgia,serif;\n"
"}\n"
"@media (prefers-color-scheme:dark){\n"
"  :root{ --bg:#16181a; --panel:#1e2124; --ink:#e8e6e1; --dim:#9a9791; --line:#333;\n"
"         --accent:#7fb3a0; --warn:#d09a6a; --mark:#232a27; }\n"
"}\n"
"*{box-sizing:border-box}\n"
"body{margin:0;background:var(--bg);color:var(--ink);\n"
"     font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n"
"header{position:sticky;top:0;z-index:5;background:var(--panel);border-bottom:1px solid var(--line)}\n"
".brand{display:flex;align-items:baseline;gap:.6rem;padding:.6rem 1rem .2rem}\n"
".brand h1{font:600 17px/1 var(--serif);margin:0;letter-spacing:.02em}\n"
".brand span{color:var(--dim);font-size:12px;font-family:var(--mono)}\n"
"nav{display:flex;gap:0;overflow-x:auto}\n"
"nav button{flex:1;min-width:88px;background:none;border:none;border-bottom:2px solid transparent;\n"
"  color:var(--dim);font:inherit;padding:.55rem .4rem;cursor:pointer}\n"
"nav button.on{color:var(--ink);border-bottom-color:var(--accent);font-weight:600}\n"
"main{max-width:52rem;margin:0 auto;padding:1rem}\n"
"section{display:none} section.on{display:block}\n"
".card{background:var(--panel);border:1px solid var(--line);border-radius:10px;\n"
"  padding:.9rem 1rem;margin-bottom:1rem}\n"
".card h2{font:600 13px/1 system-ui;letter-spacing:.09em;text-transform:uppercase;\n"
"  color:var(--dim);margin:0 0 .8rem}\n"
".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.7rem}\n"
"label{display:block;font-size:12px;color:var(--dim);margin-bottom:.2rem}\n"
"input,select{width:100%;padding:.45rem .5rem;background:var(--bg);color:var(--ink);\n"
"  border:1px solid var(--line);border-radius:6px;font:14px var(--mono)}\n"
"input:focus,select:focus{outline:2px solid var(--accent);outline-offset:-1px}\n"
".row{display:flex;gap:.5rem}.row>*{flex:1}\n"
"button.act{background:var(--accent);color:#fff;border:none;border-radius:6px;\n"
"  padding:.5rem .9rem;font:600 14px system-ui;cursor:pointer}\n"
"button.ghost{background:none;border:1px solid var(--line);color:var(--ink);\n"
"  border-radius:6px;padding:.45rem .8rem;font:14px system-ui;cursor:pointer}\n"
".tools{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}\n"
".hint{color:var(--dim);font-size:12px;margin-top:.35rem}\n"
".err{color:var(--warn)}\n"
"\n"
"/* ---- worksheet: label | typeset formula | value ---- */\n"
".work{width:100%;border-collapse:collapse;font-size:14px}\n"
".work tr{border-bottom:1px solid var(--line)}\n"
".work tr:last-child{border-bottom:none}\n"
".work tr.total td{border-top:2px solid var(--ink);font-weight:700}\n"
".work td{padding:.45rem .3rem;vertical-align:middle}\n"
".work td.k{width:7.5rem;color:var(--dim)}\n"
".work td.v{width:8.5rem;text-align:right;font-family:var(--mono);white-space:nowrap}\n"
".work td.f{font-family:var(--serif);font-size:14.5px;color:var(--ink)}\n"
".work .sub{display:block;color:var(--dim);font-size:12.5px;margin-top:.15rem}\n"
".math{font-family:var(--serif)}\n"
".math i{font-style:italic}\n"
".op{padding:0 .18em}\n"
".frac{display:inline-flex;flex-direction:column;vertical-align:-0.55em;\n"
"  text-align:center;margin:0 .18em}\n"
".frac>span:first-child{padding:0 .3em;border-bottom:1px solid currentColor}\n"
".frac>span:last-child{padding:0 .3em}\n"
".rad{border-top:1px solid currentColor;padding:0 .15em}\n"
".lops{width:100%;border-collapse:collapse;font-size:13.5px}\n"
".lops th{text-align:left;font:600 11px system-ui;letter-spacing:.07em;\n"
"  text-transform:uppercase;color:var(--dim);padding:.3rem}\n"
".lops td{padding:.4rem .3rem;border-top:1px solid var(--line);font-family:var(--mono)}\n"
".lops tr.sel td{background:var(--mark)}\n"
".lops input[type=checkbox]{width:auto}\n"
".fixline{font-family:var(--mono);font-size:15px}\n"
".big{font-size:20px;font-family:var(--mono)}\n"
".airpage{margin-bottom:1.4rem}\n"
".airtitle{text-align:center;font:600 13px/1.3 var(--serif);letter-spacing:.06em;margin:.2rem 0 .5rem}\n"
"table.air{border-collapse:collapse;width:100%;font:12px/1.25 var(--mono)}\n"
"table.air th{font:10.5px system-ui;font-weight:600;letter-spacing:.05em;color:var(--dim);\n"
"  padding:.2rem .3rem;border-bottom:1px solid var(--ink);text-align:center;white-space:nowrap}\n"
"table.air td{padding:.08rem .3rem;text-align:right;white-space:nowrap}\n"
"table.air td.ut{text-align:left;color:var(--dim)}\n"
"table.air tr.hr td{border-top:1px solid var(--line)}\n"
"table.air tr.half td{background:var(--mark)}\n"
".mag{font-size:9.5px;margin-left:.25em;color:var(--dim)}\n"
".airnote{margin:.5rem 0;font:10.5px system-ui;letter-spacing:.06em;text-align:center;color:var(--dim)}\n"
".airfoot{margin:.3rem 0 0;font:11px system-ui;color:var(--dim)}\n"
".printlink{margin-top:.6rem;font-size:12px}\n"
".subcard{margin-top:.9rem;border:1px solid var(--line);border-radius:8px;padding:.6rem .75rem;background:var(--bg)}\n"
".subcard>summary{cursor:pointer;font:600 12px system-ui;letter-spacing:.04em;color:var(--dim)}\n"
".editing{outline:2px solid var(--accent);outline-offset:2px}\n"
".matches{display:flex;gap:.4rem;flex-wrap:wrap;margin-top:.4rem}\n"
".matches button{background:var(--mark);border:1px solid var(--line);border-radius:999px;\n"
"  padding:.25rem .7rem;font:13px system-ui;color:var(--ink);cursor:pointer}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div class=\"brand\"><h1>navalm</h1><span id=\"ver\"></span></div>\n"
"  <nav>\n"
"    <button data-tab=\"sight\" class=\"on\">Sight</button>\n"
"    <button data-tab=\"almanac\">Almanac</button>\n"
"    <button data-tab=\"list\">Sights</button>\n"
"    <button data-tab=\"fix\">Fix</button>\n"
"    <button data-tab=\"setup\">Setup</button>\n"
"  </nav>\n"
"</header>\n"
"\n"
"<main>\n"
"<details class=\"card\" id=\"safety-notice\">\n"
"  <summary><strong>Informational use only. No warranty. No safety-critical reliance. Use implies acceptance of these risk terms.</strong></summary>\n"
"<p>NAVALM, its documentation, and all generated results are provided for informational and educational purposes only. They are not certified navigation products. Do not rely on them for navigation or any decision where an incorrect result, failure, or delay could cause death, personal injury, or loss of or damage to property. Independent verification does not make NAVALM suitable for safety-critical use.</p>\n"
"<p>By using NAVALM, you acknowledge this warning and agree, to the maximum extent permitted by applicable law, to use it entirely at your own risk and to assume all responsibility and liability for your use, your interpretation of its results, your decisions, and the resulting consequences. If you do not accept these terms, do not use NAVALM.</p>\n"
"<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE, DOCUMENTATION, DATA, AND OUTPUT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, RELIABILITY, AVAILABILITY, AND NONINFRINGEMENT.</p>\n"
"<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE AUTHORS, COPYRIGHT HOLDERS, CONTRIBUTORS, AND DISTRIBUTORS SHALL NOT BE LIABLE FOR ANY CLAIM, LOSS, DAMAGE, OR OTHER LIABILITY ARISING FROM OR IN CONNECTION WITH NAVALM OR ITS USE OR INABILITY TO BE USED, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE. THIS INCLUDES DEATH, PERSONAL INJURY, PROPERTY DAMAGE, NAVIGATION ERRORS, LOSS OF DATA OR PROFITS, AND DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES.</p>\n"
"<p>Nothing in this notice excludes or limits liability or rights that cannot lawfully be excluded or limited. This notice does not promise that a waiver or disclaimer is enforceable in every jurisdiction or circumstance.</p>\n"
"<p>Copyright permissions are granted by LICENSE and the applicable third-party licenses. This safety and risk notice does not amend the MIT license, add a copyright field-of-use restriction, or reduce anyone&#x27;s rights under the upstream XEphem MIT license.</p>\n"
"<p>NAVALM contributions: Copyright (c) 2026 Chris Maness, MIT license. XEphem: Copyright (c) 1990-2020 Elwood Charles Downey, MIT license. See LICENSE and THIRD_PARTY_NOTICES.md in the source distribution.</p>\n"
"<p>In memory of Dr. Thomas R. Metcalf, whose calculator navigation software inspired NAVALM. The former Metcalf-derived astronomy engine and tables have been replaced with XEphem.</p>\n"
"</details>\n"
"\n"
"<section id=\"sight\" class=\"on\">\n"
"  <div class=\"card\">\n"
"    <h2>Observation</h2>\n"
"    <div class=\"grid\">\n"
"      <div>\n"
"        <label>Body</label>\n"
"        <select id=\"body\">\n"
"          <option>sun</option><option>moon</option><option>mercury</option>\n"
"          <option>venus</option><option>mars</option><option>jupiter</option>\n"
"          <option>saturn</option><option value=\"star\">star</option>\n"
"        </select>\n"
"      </div>\n"
"      <div id=\"starwrap\" style=\"display:none\">\n"
"        <label>Star (first letters are enough)</label>\n"
"        <input id=\"star\" placeholder=\"pol\" autocomplete=\"off\">\n"
"        <div class=\"matches\" id=\"starmatches\"></div>\n"
"      </div>\n"
"      <div><label>Date UTC</label><input id=\"date\" placeholder=\"2026-09-19\"></div>\n"
"      <div><label>Time UTC</label><input id=\"time\" placeholder=\"21:38:05\"></div>\n"
"      <div><label>Hs degrees</label><input id=\"hsd\" inputmode=\"decimal\" placeholder=\"94\"></div>\n"
"      <div><label>Hs minutes</label><input id=\"hsm\" inputmode=\"decimal\" placeholder=\"37.2\"></div>\n"
"      <div id=\"limbwrap\">\n"
"        <label>Limb</label>\n"
"        <select id=\"limb\"><option value=\"ll\">lower</option>\n"
"          <option value=\"center\">center</option><option value=\"ul\">upper</option></select>\n"
"      </div>\n"
"      <div><label>Label</label><input id=\"label\" placeholder=\"LAN\"></div>\n"
"    </div>\n"
"\n"
"    <details class=\"subcard\" id=\"sightsettings\">\n"
"      <summary>This sight's settings &mdash; index error, horizon, conditions, DR, motion</summary>\n"
"      <div class=\"grid\" style=\"margin-top:.7rem\">\n"
"        <div><label>Index error, arcminutes</label><input id=\"f_ie\" inputmode=\"decimal\"></div>\n"
"        <div><label>IE is</label><select id=\"f_iearc\">\n"
"          <option value=\"off\">off arc (+)</option><option value=\"on\">on arc (&minus;)</option></select></div>\n"
"        <div><label>Horizon</label><select id=\"f_horizon\">\n"
"          <option value=\"sea\">sea</option><option value=\"ah\">artificial</option></select></div>\n"
"        <div><label>Height of eye</label><input id=\"f_he\" inputmode=\"decimal\"></div>\n"
"        <div><label>HE units</label><select id=\"f_heunit\">\n"
"          <option value=\"ft\">feet</option><option value=\"m\">metres</option></select></div>\n"
"        <div><label>Temperature &deg;C</label><input id=\"f_temp\" inputmode=\"decimal\"></div>\n"
"        <div><label>Pressure mb</label><input id=\"f_press\" inputmode=\"decimal\"></div>\n"
"        <div><label>DR latitude</label><input id=\"f_drlat\" placeholder=\"34 1.2 N\"></div>\n"
"        <div><label>DR longitude</label><input id=\"f_drlon\" placeholder=\"117 18.8 W\"></div>\n"
"        <div><label>Course &deg;T</label><input id=\"f_course\" inputmode=\"decimal\"></div>\n"
"        <div><label>Speed kt</label><input id=\"f_speed\" inputmode=\"decimal\"></div>\n"
"        <div><label>Set &deg;T</label><input id=\"f_set\" inputmode=\"decimal\"></div>\n"
"        <div><label>Drift kt</label><input id=\"f_drift\" inputmode=\"decimal\"></div>\n"
"      </div>\n"
"      <div class=\"hint\" style=\"margin-top:.5rem\">These start from the Setup defaults and belong\n"
"        to this sight alone; changing them here never changes Setup.</div>\n"
"    </details>\n"
"\n"
"    <div class=\"tools\">\n"
"      <button class=\"ghost\" id=\"now\">Now</button>\n"
"      <button class=\"ghost\" id=\"loaddef\">Reset to setup defaults</button>\n"
"      <button class=\"act\" id=\"save\">Save to sights</button>\n"
"      <button class=\"ghost\" id=\"cancel\" style=\"display:none\">Cancel edit</button>\n"
"    </div>\n"
"    <div class=\"hint\" id=\"savemsg\"></div>\n"
"    <div class=\"hint\" id=\"activedr\" style=\"margin-top:.65rem\"></div>\n"
"  </div>\n"
"\n"
"  <div class=\"card\" id=\"worked\"></div>\n"
"</section>\n"
"\n"
"\n"
"<section id=\"almanac\">\n"
"  <div class=\"card\">\n"
"    <h2>Almanac</h2>\n"
"    <div class=\"grid\">\n"
"      <div>\n"
"        <label>Body</label>\n"
"        <select id=\"a_body\">\n"
"          <option>sun</option><option>moon</option><option>mercury</option>\n"
"          <option>venus</option><option>mars</option><option>jupiter</option>\n"
"          <option>saturn</option><option>aries</option><option value=\"star\">star</option>\n"
"        </select>\n"
"      </div>\n"
"      <div id=\"a_starwrap\" style=\"display:none\">\n"
"        <label>Star</label><input id=\"a_star\" placeholder=\"vega\" autocomplete=\"off\">\n"
"      </div>\n"
"      <div><label>Date UTC</label><input id=\"a_date\" placeholder=\"2026-09-22\"></div>\n"
"      <div><label>Time UTC</label><input id=\"a_time\" placeholder=\"20:00:00\"></div>\n"
"    </div>\n"
"    <div class=\"tools\">\n"
"      <button class=\"ghost\" id=\"a_now\">Now</button>\n"
"      <button class=\"ghost\" id=\"a_naval\">NAVAL daily table</button>\n"
"      <button class=\"ghost\" id=\"a_air\">AIR daily pages</button>\n"
"    </div>\n"
"    <div class=\"hint\">Both tables open here on this tab. NAVAL uses whole-hour rows;\n"
"      AIR follows the printed Air Almanac daily pages at 10-minute steps.</div>\n"
"  </div>\n"
"  <div class=\"card\" id=\"almanacout\">\n"
"    <h2>Almanac result</h2><div class=\"hint\">Choose a body, date and UTC time.</div>\n"
"  </div>\n"
"</section>\n"
"\n"
"<section id=\"list\">\n"
"  <div class=\"card\">\n"
"    <h2>Stored sights</h2>\n"
"    <table class=\"lops\"><thead><tr>\n"
"      <th></th><th>body</th><th>time UTC</th><th>Ho</th><th>a</th><th>Zn</th><th>label</th><th></th>\n"
"    </tr></thead><tbody id=\"listbody\"></tbody></table>\n"
"    <div class=\"tools\">\n"
"      <button class=\"act\" id=\"dofix\">Fix from selected</button>\n"
"      <button class=\"ghost\" id=\"selall\">Select all</button>\n"
"      <button class=\"ghost\" id=\"export\">Export JSON</button>\n"
"      <button class=\"ghost\" id=\"importbtn\">Import JSON</button>\n"
"      <button class=\"ghost\" id=\"clear\">Clear all</button>\n"
"    </div>\n"
"    <div class=\"hint\">Sights live in this browser only. The server keeps nothing,\n"
"      and never touches ~/.naval.save.</div>\n"
"    <textarea id=\"io\" style=\"display:none;width:100%;height:9rem;margin-top:.6rem;\n"
"      font:12px var(--mono);background:var(--bg);color:var(--ink);\n"
"      border:1px solid var(--line);border-radius:6px\"></textarea>\n"
"  </div>\n"
"</section>\n"
"\n"
"<section id=\"fix\">\n"
"  <div class=\"card\"><h2>Fix</h2><div id=\"fixout\">\n"
"    <div class=\"hint\">Select two or more sights on the Sights tab, then press\n"
"      &ldquo;Fix from selected&rdquo;.</div></div></div>\n"
"  <div class=\"card\" id=\"motioncard\"><h2>Advancing</h2>\n"
"    <div class=\"hint\">Each sight is advanced from its own time to the fix time using its\n"
"      own course, speed, set and drift, so an earlier sight moves further. Set these\n"
"      per sight below.</div>\n"
"    <div id=\"motionrows\"></div>\n"
"  </div>\n"
"</section>\n"
"\n"
"<section id=\"setup\">\n"
"  <div class=\"card\">\n"
"    <h2>Defaults for new sights</h2>\n"
"    <div class=\"grid\">\n"
"      <div><label>Index error, arcminutes</label><input id=\"s_ie\" inputmode=\"decimal\"></div>\n"
"      <div><label>IE is</label><select id=\"s_iearc\">\n"
"        <option value=\"off\">off arc (+)</option><option value=\"on\">on arc (&minus;)</option></select></div>\n"
"      <div><label>Horizon</label><select id=\"s_horizon\">\n"
"        <option value=\"sea\">sea</option><option value=\"ah\">artificial</option></select></div>\n"
"      <div><label>Height of eye</label><input id=\"s_he\" inputmode=\"decimal\"></div>\n"
"      <div><label>HE units</label><select id=\"s_heunit\">\n"
"        <option value=\"ft\">feet</option><option value=\"m\">metres</option></select></div>\n"
"      <div><label>Temperature &deg;C</label><input id=\"s_temp\" inputmode=\"decimal\"></div>\n"
"      <div><label>Pressure mb</label><input id=\"s_press\" inputmode=\"decimal\"></div>\n"
"      <div><label>DR latitude</label><input id=\"s_drlat\" placeholder=\"34 2.5 N\"></div>\n"
"      <div><label>DR longitude</label><input id=\"s_drlon\" placeholder=\"117 21.9 W\"></div>\n"
"    </div>\n"
"    <div class=\"tools\"><button class=\"act\" id=\"s_save\">Save defaults</button></div>\n"
"    <div class=\"hint\" id=\"setupmsg\">Kept in this browser, separate from ~/.navalmrc.</div>\n"
"  </div>\n"
"</section>\n"
"\n"
"</main>\n"
"\n"
"<script>\n"
"'use strict';\n"
"const $ = id => document.getElementById(id);\n"
"const LS_SIGHTS = 'navalm.sights', LS_SETUP = 'navalm.setup';\n"
"\n"
"/* ---------- formatting ---------- */\n"
"const pad = (n,w)=>String(n).padStart(w,'0');\n"
"function dm(x,degw){\n"
"  const s = x<0?'\\u2212':''; x=Math.abs(x);\n"
"  let d=Math.floor(x), m=(x-d)*60;\n"
"  if(m>=59.95){m=0;d++;}\n"
"  return s+pad(d,degw)+'\\u00b0 '+(m<10?'0':'')+m.toFixed(1)+'\\u2032';\n"
"}\n"
"const alt = x=>dm(x,2);\n"
"/* single-body lookups keep hundredths of a minute; tables stay at tenths */\n"
"function dm2(x,degw){\n"
"  const s = x<0?'\\u2212':''; x=Math.abs(x);\n"
"  let d=Math.floor(x), m=(x-d)*60;\n"
"  if(m>=59.995){m=0;d++;}\n"
"  return s+pad(d,degw)+'\\u00b0 '+(m<10?'0':'')+m.toFixed(2)+'\\u2032';\n"
"}\n"
"const gha2 = x=>dm2(((x%360)+360)%360,3);\n"
"/* right ascension as degrees, minutes and seconds */\n"
"function radms(x){\n"
"  let a=((x%360)+360)%360;\n"
"  let d=Math.floor(a), m=Math.floor((a-d)*60), s=((a-d)*60-m)*60;\n"
"  if(s>=59.95){s=0;m++;}\n"
"  if(m>=60){m=0;d=(d+1)%360;}\n"
"  return pad(d,3)+'\\u00b0 '+pad(m,2)+'\\u2032 '+(s<10?'0':'')+s.toFixed(1)+'\\u2033';\n"
"}\n"
"const lat2 = x=>(x<0?'S ':'N ')+dm2(Math.abs(x),2);\n"
"const gha = x=>dm(((x%360)+360)%360,3);\n"
"const lat = x=>(x<0?'S ':'N ')+dm(Math.abs(x),2);\n"
"const lon = x=>(x<0?'W ':'E ')+dm(Math.abs(x),3);\n"
"function mins(x){\n"
"  const r=Math.round(x*10)/10;\n"
"  if(r===0) return '0.0\\u2032';\n"
"  return (r<0?'\\u2212':'+')+Math.abs(r).toFixed(1)+'\\u2032';\n"
"}\n"
"const num=(x,n)=>Number(x).toFixed(n===undefined?1:n);\n"
"\n"
"/* ---------- math typesetting (no external libraries) ---------- */\n"
"const frac=(a,b)=>`<span class=\"frac\"><span>${a}</span><span>${b}</span></span>`;\n"
"const sqrt=a=>`\\u221a<span class=\"rad\">${a}</span>`;\n"
"const v=s=>`<i>${s}</i>`;\n"
"\n"
"/* ---------- position parsing, same spirit as the TUI ---------- */\n"
"function parsePos(text,isLon){\n"
"  if(!text) return 0;\n"
"  const nums=[]; let hemi=0;\n"
"  const re=/([NSEWnsew])|(-?\\d+(?:\\.\\d+)?)/g; let m;\n"
"  while((m=re.exec(text))){\n"
"    if(m[1]){ const c=m[1].toUpperCase();\n"
"      if(c==='S'||c==='W') hemi=-1; else if(c==='N'||c==='E') hemi=1; }\n"
"    else nums.push(parseFloat(m[2]));\n"
"  }\n"
"  if(!nums.length) return 0;\n"
"  let val;\n"
"  if(nums.length===1) val=nums[0];\n"
"  else if(nums.length===2) val=Math.sign(nums[0]||1)*(Math.abs(nums[0])+nums[1]/60);\n"
"  else val=Math.sign(nums[0]||1)*(Math.abs(nums[0])+nums[1]/60+nums[2]/3600);\n"
"  if(hemi) val=hemi*Math.abs(val);\n"
"  return val;\n"
"}\n"
"\n"
"/* ---------- state ---------- */\n"
"function loadSights(){ try{ return JSON.parse(localStorage.getItem(LS_SIGHTS))||[] }catch(e){ return [] } }\n"
"function saveSights(a){ localStorage.setItem(LS_SIGHTS,JSON.stringify(a)); }\n"
"function loadSetup(){\n"
"  try{ return Object.assign(defSetup(),JSON.parse(localStorage.getItem(LS_SETUP))||{}) }\n"
"  catch(e){ return defSetup() }\n"
"}\n"
"function defSetup(){\n"
"  return {ie:0,iearc:'off',horizon:'sea',he:0,heunit:'ft',limb:'ll',\n"
"          temp:10,press:1010,drlat:34.0415,drlon:-117.3645};\n"
"}\n"
"\n"
"/* ---------- the sight form ---------- */\n"
"function renderActiveDR(){\n"
"  const st=loadSetup(), box=$('activedr');\n"
"  const la=$('f_drlat')?parsePos($('f_drlat').value):0;\n"
"  const lo=$('f_drlon')?parsePos($('f_drlon').value):0;\n"
"  const own=(la||lo);\n"
"  box.innerHTML='<b>Active DR for this sight:</b> '+lat(own?la:st.drlat)+' &nbsp; '+\n"
"    lon(own?lo:st.drlon)+' &nbsp; <span class=\"sub\">('+\n"
"    (own?'this sight\\u2019s own DR':'from Setup')+'; live values, not examples)</span>';\n"
"}\n"
"/* Which sight is being edited, or null when entering a new one. */\n"
"let editIndex=null;\n"
"\n"
"const fnum=(id,dflt)=>{ const v=parseFloat($(id).value); return isFinite(v)?v:dflt; };\n"
"\n"
"function formSight(){\n"
"  const dparts=($('date').value||'').split(/[-/ ]/).map(Number);\n"
"  const tparts=($('time').value||'').split(/[: ]/).map(Number);\n"
"  return {\n"
"    body:$('body').value, star:$('star').value.trim(),\n"
"    y:dparts[0]||2026, mo:dparts[1]||1, d:dparts[2]||1,\n"
"    h:tparts[0]||0, mi:tparts[1]||0, s:tparts[2]||0,\n"
"    hs:(parseFloat($('hsd').value)||0)+(parseFloat($('hsm').value)||0)/60,\n"
"    ie:fnum('f_ie',0), iearc:$('f_iearc').value,\n"
"    horizon:$('f_horizon').value, he:fnum('f_he',0), heunit:$('f_heunit').value,\n"
"    limb:$('limb').value, temp:fnum('f_temp',10), press:fnum('f_press',1010),\n"
"    drlat:parsePos($('f_drlat').value), drlon:parsePos($('f_drlon').value),\n"
"    label:$('label').value.trim(),\n"
"    course:fnum('f_course',0), speed:fnum('f_speed',0),\n"
"    set:fnum('f_set',0), drift:fnum('f_drift',0)\n"
"  };\n"
"}\n"
"\n"
"/* Fill every field on the Sight tab from a stored sight, or from the Setup\n"
"   defaults when called with nothing (a fresh observation). */\n"
"function fillSight(s){\n"
"  const st=loadSetup();\n"
"  const src = s || {ie:st.ie,iearc:st.iearc,horizon:st.horizon,he:st.he,heunit:st.heunit,\n"
"                    limb:st.limb||'ll',temp:st.temp,press:st.press,\n"
"                    drlat:st.drlat,drlon:st.drlon,course:0,speed:0,set:0,drift:0};\n"
"  if(s){\n"
"    $('body').value=s.body; $('star').value=s.star||'';\n"
"    $('date').value=s.y+'-'+pad(s.mo,2)+'-'+pad(s.d,2);\n"
"    $('time').value=pad(s.h,2)+':'+pad(s.mi,2)+':'+pad(Math.round(s.s),2);\n"
"    const deg=Math.floor(s.hs), min=(s.hs-deg)*60;\n"
"    $('hsd').value=deg; $('hsm').value=min.toFixed(1);\n"
"    $('label').value=s.label||'';\n"
"  }\n"
"  $('f_ie').value=src.ie; $('f_iearc').value=src.iearc;\n"
"  $('f_horizon').value=src.horizon; $('f_he').value=src.he; $('f_heunit').value=src.heunit;\n"
"  $('limb').value=src.limb||'ll';\n"
"  $('f_temp').value=src.temp; $('f_press').value=src.press;\n"
"  $('f_drlat').value=src.drlat?lat(src.drlat):''; $('f_drlon').value=src.drlon?lon(src.drlon):'';\n"
"  $('f_course').value=src.course||''; $('f_speed').value=src.speed||'';\n"
"  $('f_set').value=src.set||''; $('f_drift').value=src.drift||'';\n"
"  $('starwrap').style.display=($('body').value==='star')?'':'none';\n"
"  $('limbwrap').style.display=(['sun','moon'].includes($('body').value))?'':'none';\n"
"}\n"
"\n"
"/* Open a stored sight for editing: every field, including the ones that\n"
"   normally come from Setup, so one change does not mean retyping the shot. */\n"
"function editSight(i){\n"
"  const arr=loadSights();\n"
"  if(i<0 || i>=arr.length) return;\n"
"  editIndex=i;\n"
"  fillSight(arr[i]);\n"
"  $('sightsettings').open=true;\n"
"  $('sightsettings').classList.add('editing');\n"
"  $('save').textContent='Update sight';\n"
"  $('cancel').style.display='';\n"
"  $('savemsg').textContent='Editing sight '+(i+1)+' of '+arr.length+'. Every field is shown.';\n"
"  show('sight');\n"
"  refresh();\n"
"}\n"
"\n"
"function endEdit(msg){\n"
"  editIndex=null;\n"
"  $('sightsettings').open=false;\n"
"  $('sightsettings').classList.remove('editing');\n"
"  $('save').textContent='Save to sights';\n"
"  $('cancel').style.display='none';\n"
"  $('savemsg').textContent=msg||'';\n"
"}\n"
"function query(s,i){\n"
"  const k=n=>(i===undefined?n:n+i);\n"
"  const p=new URLSearchParams();\n"
"  const add=(n,v)=>p.set(k(n),v);\n"
"  add('body',s.body); add('star',s.star||'');\n"
"  add('y',s.y); add('mo',s.mo); add('d',s.d); add('h',s.h); add('mi',s.mi); add('s',s.s);\n"
"  add('hs',s.hs); add('ie',s.ie); add('iearc',s.iearc); add('horizon',s.horizon);\n"
"  add('he',s.he); add('heunit',s.heunit); add('limb',s.limb);\n"
"  add('temp',s.temp); add('press',s.press); add('drlat',s.drlat); add('drlon',s.drlon);\n"
"  add('label',s.label||'');\n"
"  add('course',s.course||0); add('speed',s.speed||0);\n"
"  add('set',s.set||0); add('drift',s.drift||0);\n"
"  return p.toString();\n"
"}\n"
"\n"
"/* ---------- worked sight ---------- */\n"
"function row(k,formula,value,cls){\n"
"  return `<tr class=\"${cls||''}\"><td class=\"k\">${k}</td>\n"
"    <td class=\"f\">${formula||''}</td><td class=\"v\">${value||''}</td></tr>`;\n"
"}\n"
"function renderWorked(r){\n"
"  if(r.error) return `<h2>Worked sight</h2><p class=\"err\">${r.error}</p>`;\n"
"  const AH=r.artificial, moon=(r.body==='moon');\n"
"  let h='<h2>Hs to Ho</h2><table class=\"work\">';\n"
"  h+=row('Hs','sextant altitude',alt(r.hs));\n"
"  h+=row('IC',`${v('Hs')} ${r.ie_min?(r.ie_on_arc?'\\u2212':'+'):'\\u00b1'} ${num(Math.abs(r.ie_min),1)}\\u2032 &nbsp;<span class=\"sub\">index error ${r.ie_on_arc?'on':'off'} the arc</span>`,mins(r.ic_min));\n"
"  if(AH){\n"
"    h+=row('Ha',`${frac(v('Hs')+' + IC','2')}<span class=\"sub\">artificial horizon: the reading is a double altitude, and there is no dip</span>`,alt(r.ha));\n"
"  }else{\n"
"    h+=row('Dip',`${num(r.he_metres?1.76:0.97,2)}\\u2032 ${sqrt(num(r.he,1)+(r.he_metres?' m':' ft'))}`,mins(-r.dip_min));\n"
"    h+=row('Ha',`${v('Hs')} + IC \\u2212 dip`,alt(r.ha));\n"
"  }\n"
"  h+=row('R<sub>0</sub>',\n"
"    `${frac('0.0167\\u00b0','tan('+v('Ha')+' + '+frac('7.32',v('Ha')+' + 4.32')+')')}\n"
"     <span class=\"sub\">= 0.0167\\u00b0 / tan(${num(r.ha,2)}\\u00b0 + 7.32/(${num(r.ha,2)} + 4.32)) = ${num(r.r0_min,2)}\\u2032</span>`,\n"
"    mins(-r.r0_min));\n"
"  h+=row('f',\n"
"    `${frac('0.28 '+v('P'),v('T')+' + 273')}\n"
"     <span class=\"sub\">= 0.28 \\u00d7 ${num(r.press_mb,1)} mb / ${num(r.temp_c+273,1)} K</span>`,\n"
"    num(r.f,4));\n"
"  h+=row('R',`${v('f')} \\u00d7 R<sub>0</sub>`,mins(-r.r_min));\n"
"  if(r.used_sd){\n"
"    const lab=(r.limb>0?'lower':'upper')+' limb';\n"
"    h+=row('SD',\n"
"      moon ? `SD<span class=\"op\">\\u00b7</span>(1 + sin HP<span class=\"op\">\\u00b7</span>sin ${v('H')})\n"
"              <span class=\"sub\">${lab}: ${num(r.sd_raw_min,2)}\\u2032 augmented to ${num(Math.abs(r.sd_min),2)}\\u2032</span>`\n"
"           : `almanac semidiameter<span class=\"sub\">${lab}: ${num(r.sd_raw_min,2)}\\u2032</span>`,\n"
"      mins(r.sd_min));\n"
"  }\n"
"  if(r.used_par)\n"
"    h+=row('P<sub>a</sub>',\n"
"      `arcsin(sin HP<span class=\"op\">\\u00b7</span>cos ${v('H')})\n"
"       <span class=\"sub\">HP = ${num(r.hp_min,2)}\\u2032</span>`,\n"
"      mins(r.par_min));\n"
"  h+=row('Ho','observed altitude',alt(r.ho),'total');\n"
"  h+='</table>';\n"
"\n"
"  if(!r.has_dr){\n"
"    h+='<p class=\"hint\">Set a DR on the Setup tab to reduce this sight to a line of position.</p>';\n"
"    return h;\n"
"  }\n"
"\n"
"  /* almanac */\n"
"  h+='<h2 style=\"margin-top:1.2rem\">Almanac</h2><table class=\"work\">';\n"
"  if(r.is_star){\n"
"    h+=row('GHA \\u2648 '+pad(r.hour_h,2)+'h','hourly page',gha(r.gha_aries_hour));\n"
"    h+=row('Increment',`${num(r.frac_hour*60,2)} min \\u00d7 15\\u00b0 02.46\\u2032/h`,gha(r.inc_deg));\n"
"    h+=row('GHA \\u2648','',gha(r.gha_aries));\n"
"    h+=row('SHA',r.star,gha(r.sha_deg));\n"
"    h+=row('GHA','GHA \\u2648 + SHA',gha(r.gha));\n"
"    h+=row('Dec','',lat(r.dec));\n"
"  }else{\n"
"    const rate=moon?'14\\u00b0 19.0\\u2032/h':'15\\u00b0 00.0\\u2032/h';\n"
"    h+=row('GHA '+pad(r.hour_h,2)+'h','hourly page',gha(r.gha_hour));\n"
"    h+=row('Increment',`${num(r.frac_hour*60,2)} min \\u00d7 ${rate}`,gha(r.inc_deg));\n"
"    if(r.has_v) h+=row('v corr',`${v('v')} \\u00d7 ${num(r.frac_hour,4)} h &nbsp;<span class=\"sub\">v = ${mins(r.v_min)} per hour</span>`,mins(r.vcorr_min));\n"
"    h+=row('GHA','',gha(r.gha));\n"
"    h+=row('Dec '+pad(r.hour_h,2)+'h','hourly page',lat(r.dec_hour));\n"
"    h+=row('d corr',`${v('d')} \\u00d7 ${num(r.frac_hour,4)} h &nbsp;<span class=\"sub\">d = ${mins(r.d_min)} per hour, + when |Dec| grows</span>`,mins(r.dcorr_min));\n"
"    h+=row('Dec','',lat(r.dec));\n"
"    let dg=(r.gha_exact-r.gha)*60; while(dg>10800)dg-=21600; while(dg<-10800)dg+=21600;\n"
"    h+=row('check',`engine at the exact second<span class=\"sub\">Dec ${mins((r.dec_exact-r.dec)*60)}</span>`,mins(dg));\n"
"  }\n"
"  h+='</table>';\n"
"\n"
"  /* assumed position and HO 229 */\n"
"  h+='<h2 style=\"margin-top:1.2rem\">Assumed position</h2><table class=\"work\">';\n"
"  h+=row('a-Lat','DR latitude to the whole degree',lat(r.ap_lat));\n"
"  h+=row('a-Lon','minutes chosen for a whole-degree LHA',lon(r.ap_lon));\n"
"  h+=row('LHA','GHA + a-Lon',pad(r.lha,3)+'\\u00b0');\n"
"  h+='</table>';\n"
"\n"
"  h+=`<h2 style=\"margin-top:1.2rem\">HO 229 &nbsp;<span style=\"font-weight:400;text-transform:none;letter-spacing:0\">LHA ${pad(r.lha,3)}\\u00b0, Lat ${Math.abs(Math.round(r.ap_lat))}\\u00b0 ${r.ap_lat<0?'S':'N'}, Dec ${r.dec_deg_whole}\\u00b0 ${r.same_name?'same':'contrary'} name</span></h2><table class=\"work\">`;\n"
"  h+=row('Tab Hc','tabulated for the whole degree of Dec',alt(r.tab_hc_min/60));\n"
"  h+=row('d','change in Hc per degree of Dec',mins(r.d_tab_min));\n"
"  h+=row('Dec inc','',num(r.dec_inc_min,1)+'\\u2032');\n"
"  h+=row('d corr',`${frac(v('d')+' \\u00d7 Dec inc','60')}`,mins(r.dcorr229_min));\n"
"  if(Math.abs(r.secdiff_min)>=0.05) h+=row('2nd diff','second-difference residual',mins(r.secdiff_min));\n"
"  h+=row('Hc','',alt(r.hc_min/60));\n"
"  h+=row('Z',`arccos ${frac('sin Dec \\u2212 sin Lat<span class=\"op\">\\u00b7</span>sin '+v('Hc'),'cos Lat<span class=\"op\">\\u00b7</span>cos '+v('Hc'))}`,\n"
"        (r.ap_lat<0?'S':'N')+' '+num(r.z,1)+'\\u00b0 '+(r.lha>180?'E':'W'));\n"
"  h+=row('Zn','from Z by the LHA rule',pad(Math.round(r.zn),3)+'\\u00b0');\n"
"  h+='</table>';\n"
"\n"
"  h+='<h2 style=\"margin-top:1.2rem\">Line of position</h2><table class=\"work\">';\n"
"  h+=row('Ho','',alt(r.ho));\n"
"  h+=row('Hc','',alt(r.hc_min/60));\n"
"  h+=row('Intercept',`${v('a')} = Ho \\u2212 Hc &nbsp;<span class=\"sub\">${r.intercept_nm>=0?'Ho greater: toward':'Ho less: away'}</span>`,\n"
"        num(Math.abs(r.intercept_nm),1)+' NM '+(r.intercept_nm>=0?'T':'A'),'total');\n"
"  h+='</table>';\n"
"  return h;\n"
"}\n"
"\n"
"let reduceTimer=null;\n"
"function refresh(){\n"
"  clearTimeout(reduceTimer);\n"
"  reduceTimer=setTimeout(async ()=>{\n"
"    const s=formSight();\n"
"    if(!(s.hs>0)){ $('worked').innerHTML='<h2>Worked sight</h2><p class=\"hint\">Enter Hs to see the worked sight.</p>'; return; }\n"
"    try{\n"
"      const r=await (await fetch('/api/reduce?'+query(s))).json();\n"
"      $('worked').innerHTML=renderWorked(r);\n"
"    }catch(e){ $('worked').innerHTML='<h2>Worked sight</h2><p class=\"err\">server not reachable</p>'; }\n"
"  },120);\n"
"}\n"
"\n"
"/* ---------- star matching ---------- */\n"
"async function starMatch(){\n"
"  const q=$('star').value.trim();\n"
"  const box=$('starmatches');\n"
"  box.innerHTML='';\n"
"  if(!q) return;\n"
"  const r=await (await fetch('/api/stars?q='+encodeURIComponent(q))).json();\n"
"  if(r.count===1 && r.matches[0].toLowerCase()===q.toLowerCase()) return;\n"
"  if(r.count>9){ box.innerHTML='<span class=\"hint\">'+r.count+' stars match; type another letter</span>'; return; }\n"
"  r.matches.forEach(n=>{\n"
"    const b=document.createElement('button');\n"
"    b.textContent=n;\n"
"    b.onclick=()=>{ $('star').value=n; box.innerHTML=''; refresh(); };\n"
"    box.appendChild(b);\n"
"  });\n"
"}\n"
"\n"
"\n"
"/* ---------- almanac ---------- */\n"
"function almanacQuery(){\n"
"  const dp=($('a_date').value||'').split(/[-/ ]/).map(Number);\n"
"  const tp=($('a_time').value||'').split(/[: ]/).map(Number);\n"
"  const p=new URLSearchParams();\n"
"  p.set('body',$('a_body').value);\n"
"  p.set('star',$('a_star').value.trim());\n"
"  p.set('y',dp[0]||2026); p.set('mo',dp[1]||1); p.set('d',dp[2]||1);\n"
"  p.set('h',tp[0]||0); p.set('mi',tp[1]||0); p.set('s',tp[2]||0);\n"
"  return p.toString();\n"
"}\n"
"async function refreshAlmanac(){\n"
"  const box=$('almanacout');\n"
"  try{\n"
"    const r=await (await fetch('/api/almanac?'+almanacQuery())).json();\n"
"    if(r.error){ box.innerHTML='<h2>Almanac result</h2><p class=\"err\">'+r.error+'</p>'; return; }\n"
"    let h='<h2>Almanac result</h2><table class=\"work\">';\n"
"    h+=row('Body','',r.name||'');\n"
"    h+=row('UTC','',`${r.y}-${pad(r.mo,2)}-${pad(r.d,2)} ${pad(r.h,2)}:${pad(r.mi,2)}:${pad(Math.round(r.s),2)}`);\n"
"    if(r.is_star){\n"
"      h+=row('GHA','Greenwich hour angle',gha2(r.gha));\n"
"      h+=row('SHA','sidereal hour angle',gha2(r.sha));\n"
"      h+=row('Dec','apparent declination',lat2(r.dec));\n"
"      h+=row('RA','apparent right ascension',radms(r.ra));\n"
"      h+=row('Mag','visual magnitude',num(r.mag,2));\n"
"    }else{\n"
"      h+=row('GHA','Greenwich hour angle',gha2(r.gha));\n"
"      if(r.body!=='aries') h+=row('Dec','apparent declination',lat2(r.dec));\n"
"      if(r.body!=='aries') h+=row('RA','apparent right ascension',radms(r.ra));\n"
"      if(r.hp_min>0.0005) h+=row('HP','horizontal parallax',num(r.hp_min,2)+'\\u2032');\n"
"      if(r.sd_min>0.0005) h+=row('SD','semidiameter',num(r.sd_min,2)+'\\u2032');\n"
"    }\n"
"    h+='</table>';\n"
"    box.innerHTML=h;\n"
"  }catch(e){\n"
"    box.innerHTML='<h2>Almanac result</h2><p class=\"err\">Could not reach the almanac endpoint.</p>';\n"
"  }\n"
"}\n"
"function setAlmanacNow(){\n"
"  const d=new Date();\n"
"  $('a_date').value=d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1,2)+'-'+pad(d.getUTCDate(),2);\n"
"  $('a_time').value=pad(d.getUTCHours(),2)+':'+pad(d.getUTCMinutes(),2)+':'+pad(d.getUTCSeconds(),2);\n"
"}\n"
"\n"
"async function dailyAlmanac(style){\n"
"  const dp=($('a_date').value||'').split(/[-/ ]/).map(Number);\n"
"  const p=new URLSearchParams();\n"
"  p.set('style',style); p.set('y',dp[0]||2026); p.set('mo',dp[1]||1); p.set('d',dp[2]||1);\n"
"  const box=$('almanacout');\n"
"  box.innerHTML='<h2>Almanac table</h2><div class=\"hint\">Building table&hellip;</div>';\n"
"  try{\n"
"    const r=await fetch('/api/daily?'+p.toString());\n"
"    const q='y='+(dp[0]||2026)+'&mo='+(dp[1]||1)+'&d='+(dp[2]||1);\n"
"    box.innerHTML=await r.text()\n"
"      +'<div class=\"printlink\"><a href=\"/daily/'+(style==='air'?'air':'naval')+'?'+q\n"
"      +'\" target=\"_blank\" rel=\"noopener\">Open a printable page in a new tab</a></div>';\n"
"  }catch(e){ box.innerHTML='<h2>Almanac table</h2><p class=\"err\">Could not reach the daily-table endpoint.</p>'; }\n"
"}\n"
"\n"
"/* ---------- stored sights ---------- */\n"
"async function renderList(){\n"
"  const arr=loadSights(), tb=$('listbody');\n"
"  tb.innerHTML='';\n"
"  if(!arr.length){ tb.innerHTML='<tr><td colspan=\"8\" class=\"hint\">No sights yet.</td></tr>'; return; }\n"
"  for(let i=0;i<arr.length;i++){\n"
"    const s=arr[i];\n"
"    let r={};\n"
"    try{ r=await (await fetch('/api/reduce?'+query(s))).json(); }catch(e){}\n"
"    const tr=document.createElement('tr');\n"
"    if(s.sel) tr.className='sel';\n"
"    tr.innerHTML=`<td><input type=\"checkbox\" ${s.sel?'checked':''}></td>\n"
"      <td>${s.body==='star'?s.star:s.body}</td>\n"
"      <td>${s.y}-${pad(s.mo,2)}-${pad(s.d,2)} ${pad(s.h,2)}:${pad(s.mi,2)}:${pad(Math.round(s.s),2)}</td>\n"
"      <td>${r.ok?alt(r.ho):'\\u2014'}</td>\n"
"      <td>${r.ok&&r.has_dr?num(Math.abs(r.intercept_nm),1)+' '+(r.intercept_nm>=0?'T':'A'):'\\u2014'}</td>\n"
"      <td>${r.ok&&r.has_dr?pad(Math.round(r.zn),3):'\\u2014'}</td>\n"
"      <td>${s.label||''}</td>\n"
"      <td class=\"rowacts\"><button class=\"ghost edit\" style=\"padding:.15rem .5rem\">edit</button>\n"
"        <button class=\"ghost del\" style=\"padding:.15rem .5rem\">delete</button></td>`;\n"
"    tr.querySelector('input').onchange=e=>{ arr[i].sel=e.target.checked; saveSights(arr); renderList(); renderMotion(); };\n"
"    tr.querySelector('button.edit').onclick=()=>editSight(i);\n"
"    tr.querySelector('button.del').onclick=()=>{\n"
"      if(editIndex===i) endEdit('');\n"
"      arr.splice(i,1); saveSights(arr); renderList(); renderMotion(); };\n"
"    tb.appendChild(tr);\n"
"  }\n"
"}\n"
"\n"
"function renderMotion(){\n"
"  const arr=loadSights().map((s,i)=>({s,i})).filter(o=>o.s.sel);\n"
"  const box=$('motionrows');\n"
"  if(!arr.length){ box.innerHTML='<div class=\"hint\">No sights selected.</div>'; return; }\n"
"  box.innerHTML='';\n"
"  arr.forEach(({s,i})=>{\n"
"    const d=document.createElement('div');\n"
"    d.style.marginTop='.7rem';\n"
"    d.innerHTML=`<label>${s.body==='star'?s.star:s.body} ${pad(s.h,2)}:${pad(s.mi,2)} ${s.label||''}</label>\n"
"      <div class=\"row\">\n"
"        <input placeholder=\"course\" value=\"${s.course||''}\">\n"
"        <input placeholder=\"speed kt\" value=\"${s.speed||''}\">\n"
"        <input placeholder=\"set\" value=\"${s.set||''}\">\n"
"        <input placeholder=\"drift kt\" value=\"${s.drift||''}\">\n"
"      </div>`;\n"
"    const ins=d.querySelectorAll('input');\n"
"    ins.forEach((inp,k)=>{\n"
"      inp.onchange=()=>{\n"
"        const a=loadSights();\n"
"        const val=parseFloat(inp.value)||0;\n"
"        if(k===0)a[i].course=val; else if(k===1)a[i].speed=val;\n"
"        else if(k===2)a[i].set=val; else a[i].drift=val;\n"
"        saveSights(a);\n"
"      };\n"
"    });\n"
"    box.appendChild(d);\n"
"  });\n"
"}\n"
"\n"
"async function doFix(){\n"
"  const sel=loadSights().filter(s=>s.sel);\n"
"  show('fix');\n"
"  if(sel.length<2){ $('fixout').innerHTML='<p class=\"hint\">Select at least two sights.</p>'; return; }\n"
"  const p=new URLSearchParams(); p.set('n',sel.length);\n"
"  let qs='n='+sel.length;\n"
"  sel.forEach((s,i)=>{ qs+='&'+query(s,i); });\n"
"  const r=await (await fetch('/api/fix?'+qs)).json();\n"
"  if(r.error){ $('fixout').innerHTML='<p class=\"err\">'+r.error+'</p>'; return; }\n"
"  let h=`<p class=\"hint\">Fix at ${r.fy}-${pad(r.fmo,2)}-${pad(r.fd,2)}\n"
"     ${pad(r.fh,2)}:${pad(r.fmi,2)}:${pad(Math.round(r.fs),2)} UTC from ${r.lops.length} lines</p>`;\n"
"  h+='<table class=\"lops\"><thead><tr><th>body</th><th>Zn</th><th>a</th><th>advanced</th><th>residual</th></tr></thead><tbody>';\n"
"  r.lops.forEach(l=>{\n"
"    h+=`<tr><td>${l.name}</td><td>${pad(Math.round(l.zn),3)}\\u00b0</td>\n"
"      <td>${num(Math.abs(l.intercept_nm),1)} ${l.intercept_nm>=0?'T':'A'}</td>\n"
"      <td>${l.advanced_nm>0.05?num(l.advanced_nm,1)+' NM '+pad(Math.round(l.advanced_brg),3)+'\\u00b0':'\\u2014'}</td>\n"
"      <td>${mins(l.residual_nm*60)==='0.0\\u2032'?num(l.residual_nm,2):num(l.residual_nm,2)} NM</td></tr>`;\n"
"  });\n"
"  h+='</tbody></table>';\n"
"  h+=`<p class=\"big\" style=\"margin-top:1rem\">${lat(r.lat)} &nbsp; ${lon(r.lon)}</p>`;\n"
"  h+=`<p class=\"fixline\">RMS ${num(r.rms_nm,2)} NM`;\n"
"  h+= r.have_ellipse\n"
"      ? ` &nbsp;|&nbsp; 1\\u03c3 ellipse ${num(r.semi_major_nm,2)} \\u00d7 ${num(r.semi_minor_nm,2)} NM, major axis ${pad(Math.round(r.ellipse_brg),3)}\\u00b0</p>`\n"
"      : ` &nbsp;|&nbsp; two lines: an intersection, with nothing spare to estimate error</p>`;\n"
"  h+='<div class=\"tools\"><button class=\"act\" id=\"usedr\">Use as DR</button></div>';\n"
"  $('fixout').innerHTML=h;\n"
"  $('usedr').onclick=()=>{\n"
"    const st=loadSetup(); st.drlat=r.lat; st.drlon=r.lon;\n"
"    localStorage.setItem(LS_SETUP,JSON.stringify(st));\n"
"    fillSetup(); renderActiveDR(); refresh(); renderList();\n"
"    $('usedr').textContent='DR updated';\n"
"  };\n"
"}\n"
"\n"
"/* ---------- setup ---------- */\n"
"function fillSetup(){\n"
"  const s=loadSetup();\n"
"  $('s_ie').value=s.ie; $('s_iearc').value=s.iearc; $('s_horizon').value=s.horizon;\n"
"  $('s_he').value=s.he; $('s_heunit').value=s.heunit;\n"
"  $('s_temp').value=s.temp; $('s_press').value=s.press;\n"
"  $('s_drlat').value=s.drlat?lat(s.drlat):''; $('s_drlon').value=s.drlon?lon(s.drlon):'';\n"
"}\n"
"function saveSetup(){\n"
"  const s={ie:parseFloat($('s_ie').value)||0,iearc:$('s_iearc').value,\n"
"    horizon:$('s_horizon').value,he:parseFloat($('s_he').value)||0,\n"
"    heunit:$('s_heunit').value,limb:'ll',\n"
"    temp:parseFloat($('s_temp').value)||10,press:parseFloat($('s_press').value)||1010,\n"
"    drlat:parsePos($('s_drlat').value),drlon:parsePos($('s_drlon').value)};\n"
"  localStorage.setItem(LS_SETUP,JSON.stringify(s));\n"
"  fillSetup(); renderActiveDR();\n"
"  $('setupmsg').textContent='Saved in this browser.';\n"
"  refresh();\n"
"}\n"
"\n"
"/* ---------- tabs and wiring ---------- */\n"
"function show(id){\n"
"  document.querySelectorAll('section').forEach(s=>s.classList.toggle('on',s.id===id));\n"
"  document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===id));\n"
"  if(id==='list'){ renderList(); }\n"
"  if(id==='fix'){ renderMotion(); }\n"
"}\n"
"document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.tab));\n"
"\n"
"['a_body','a_star','a_date','a_time'].forEach(id=>{\n"
"  $(id).addEventListener('input',refreshAlmanac);\n"
"  $(id).addEventListener('change',refreshAlmanac);\n"
"});\n"
"$('a_body').addEventListener('change',()=>{\n"
"  $('a_starwrap').style.display=$('a_body').value==='star'?'':'none';\n"
"});\n"
"$('a_now').onclick=()=>{ setAlmanacNow(); refreshAlmanac(); };\n"
"$('a_naval').onclick=()=>dailyAlmanac('naval');\n"
"$('a_air').onclick=()=>dailyAlmanac('air');\n"
"\n"
"function setNow(){\n"
"  const d=new Date();\n"
"  $('date').value=d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1,2)+'-'+pad(d.getUTCDate(),2);\n"
"  $('time').value=pad(d.getUTCHours(),2)+':'+pad(d.getUTCMinutes(),2)+':'+pad(d.getUTCSeconds(),2);\n"
"}\n"
"\n"
"['body','limb','date','time','hsd','hsm','label',\n"
" 'f_ie','f_iearc','f_horizon','f_he','f_heunit','f_temp','f_press',\n"
" 'f_drlat','f_drlon','f_course','f_speed','f_set','f_drift'].forEach(id=>{\n"
"  $(id).addEventListener('input',()=>{ refresh(); renderActiveDR(); });\n"
"  $(id).addEventListener('change',()=>{ refresh(); renderActiveDR(); });\n"
"});\n"
"$('body').addEventListener('change',()=>{\n"
"  const isStar=$('body').value==='star';\n"
"  $('starwrap').style.display=isStar?'':'none';\n"
"  $('limbwrap').style.display=(['sun','moon'].includes($('body').value))?'':'none';\n"
"});\n"
"$('star').addEventListener('input',()=>{ starMatch(); refresh(); });\n"
"$('now').onclick=()=>{ setNow(); refresh(); };\n"
"$('loaddef').onclick=()=>{\n"
"  const st=loadSetup();\n"
"  $('f_ie').value=st.ie; $('f_iearc').value=st.iearc; $('f_horizon').value=st.horizon;\n"
"  $('f_he').value=st.he; $('f_heunit').value=st.heunit;\n"
"  $('f_temp').value=st.temp; $('f_press').value=st.press;\n"
"  $('f_drlat').value=st.drlat?lat(st.drlat):''; $('f_drlon').value=st.drlon?lon(st.drlon):'';\n"
"  refresh();\n"
"  $('savemsg').textContent='This sight now uses the current setup defaults.';\n"
"};\n"
"$('save').onclick=()=>{\n"
"  const s=formSight();\n"
"  if(!(s.hs>0)){ $('savemsg').textContent='Enter Hs first.'; return; }\n"
"  const arr=loadSights();\n"
"  if(editIndex!==null && editIndex<arr.length){\n"
"    s.sel=arr[editIndex].sel;\n"
"    arr[editIndex]=s;\n"
"    saveSights(arr);\n"
"    const n=editIndex+1;\n"
"    endEdit('Sight '+n+' updated.');\n"
"    renderList(); renderMotion();\n"
"    show('list');\n"
"    return;\n"
"  }\n"
"  s.sel=true; arr.push(s); saveSights(arr);\n"
"  $('savemsg').textContent='Saved. '+arr.length+' sight'+(arr.length>1?'s':'')+' stored in this browser.';\n"
"  renderList();\n"
"};\n"
"$('cancel').onclick=()=>{ endEdit('Edit cancelled.'); fillSight(null); refresh(); };\n"
"$('dofix').onclick=doFix;\n"
"$('selall').onclick=()=>{ const a=loadSights(); a.forEach(s=>s.sel=true); saveSights(a); renderList(); renderMotion(); };\n"
"$('clear').onclick=()=>{ if(confirm('Remove every stored sight?')){ saveSights([]); renderList(); renderMotion(); } };\n"
"$('export').onclick=()=>{ const t=$('io'); t.style.display='block'; t.value=JSON.stringify(loadSights(),null,1); t.select(); };\n"
"$('importbtn').onclick=()=>{\n"
"  const t=$('io');\n"
"  if(t.style.display==='none'){ t.style.display='block'; t.value=''; t.placeholder='paste exported JSON, then press Import again'; return; }\n"
"  try{ const a=JSON.parse(t.value); if(Array.isArray(a)){ saveSights(a); renderList(); t.style.display='none'; } }\n"
"  catch(e){ alert('that is not the exported JSON'); }\n"
"};\n"
"$('s_save').onclick=saveSetup;\n"
"\n"
"(async function init(){\n"
"  try{ const v=await (await fetch('/api/version')).json(); $('ver').textContent='v'+v.version; }catch(e){}\n"
"  setNow(); setAlmanacNow(); fillSetup(); fillSight(null); renderActiveDR();\n"
"  $('limbwrap').style.display='';\n"
"  refresh(); refreshAlmanac(); renderList();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
#endif
